name: docker
version: 4.5.0-alpha.8
description: Simple library for viewing and controlling docker images and containers.
repository: https://github.com/open-runtime/docker.git
publish_to: none
environment:
  sdk: '>=3.3.0 <4.5.0'
dependencies:
  args: ^2.5.0
  path: ^1.9.0
  dcli:
dev_dependencies:
  lint_hard: ^4.0.0
  test: ^1.25.7
